# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "thinkpad-acpi" "acpi-call" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [
    config.boot.kernelPackages.acpi_call
  ];
  boot.kernelParams = [
    "thinkpad_acpi.fan_control=1"
  ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/36ff4f11-9e04-43db-8374-afa082d4a397";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3A27-D3B6";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/Games" =
    { device = "/dev/disk/by-uuid/b516c856-3e25-4d96-b2b6-60b869adb343";
      fsType = "ext4";
      options = [ "nofail" "x-systemd.automount" ];
    };

  fileSystems."/mnt/Archive" =
    { device = "nixos-nas:/Archive";
      fsType = "nfs";
      options = [ "nofail" "x-systemd.automount" "x-systemd.idle-timeout=300" ];
    };

  swapDevices = [ {
    device = "/swapfile";
    size = 16*1024;
  } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp5s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wwp0s20f0u9.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
